name: polysculpture
favicon: null
layout_spectrum: 0.75626
typography_spectrum: 0.26335
title: Polysculpture
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d6e7f1'
    - '#5a9db0'
    - '#9e6343'
    - '#f3ab93'
    - '#4a3427'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.9375
  rhythmicContrast: 1
purpose:
  - name: follow
    item: ca792709-0c0e-46b6-8577-653909fd1504
    url: null
