name: polysculpture
favicon: null
layout_spectrum: 1
title: Polysculpture
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d6e7f1'
    - '#5a9db0'
    - '#9e6343'
    - '#f3ab93'
    - '#4a3427'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: 90f7fce8-75e5-4a2e-a227-9ce85a542d88
    url: null
