name: polysculpture
favicon: null
layout_spectrum: 0.7573
typography_spectrum: 0.26335
title: Polysculpture
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#38373f'
    - '#a88c9a'
    - '#d4c6d3'
    - '#fdfcfc'
  brandStrength: 0.3125
  lightness: 0.001611154
  saturation: 0.9375
  rhythmicContrast: 1
purpose:
  - name: follow
    url: null
    item: ca792709-0c0e-46b6-8577-653909fd1504
